package com.github.cangoksel.il;

import com.github.cangoksel.common.utils.Displayable;

public enum Ulke implements Displayable {
    ANDORRA("Andorra", "AD", "043", "Andorra"),
    U_A_E("Birleşik Arap Emirlikleri", "AE", "647", "U.A.E"),
    AFGHANISTAN("Afganistan", "AF", "660", "Afghanistan"),
    ANTIGUA_AND_BARBUDA("Antigua ve Barbuda", "AG", "459", "Antigua And Barbuda"),
    ANGUILLA("Anguilla", "AI", "446", "Anguilla"),
    ALBANIA("Arnavutluk", "AL", "070", "Albania"),
    ARMENIA("Ermenistan", "AM", "077", "Armenia"),
    NETHERLANDS_ANTILLES("Hollanda Antilleri", "AN", "478", "Netherlands Antilles"),
    ANGOLA("Angola", "AO", "330", "Angola"),
    ANTARCTICA("Antartika", "AQ", "891", "Antarctica"),
    ARGENTINA("Arjantin", "AR", "528", "Argentina"),
    AMERICAN_SAMOA("Amerikan Samoa", "AS", "830", "American Samoa"),
    AUSTRIA("Avusturya", "AT", "038", "Austria"),
    AUSTRALIA("Avustralya", "AU", "800", "Australia"),
    ARUBA("Aruba", "AW", "474", "Aruba"),
    AZERBAIJAN("Azerbeycan", "AZ", "078", "Azerbaijan"),
    BOSNIA_HERZEGOVINA("Bosna Hersek", "BA", "093", "Bosnia-Herzegovina"),
    BARBADOS("Barbados", "BB", "469", "Barbados"),
    BANGLADESH("Bangladeş", "BD", "666", "Bangladesh"),
    BELGIUM("Belçika", "BE", "017", "Belgium"),
    BURKINA_FASO("Burkina Faso", "BF", "236", "Burkina Faso"),
    BULGARIA("Bulgaristan", "BG", "068", "Bulgaria"),
    BAHRAIN("Bahreyn", "BH", "640", "Bahrain"),
    BURUNDI("Burundi", "BI", "328", "Burundi"),
    BENIN("Benin", "BJ", "284", "Benin"),
    BERMUDA("Bermuda", "BM", "413", "Bermuda"),
    BRUNEI("Brunei Drussalam", "BN", "703", "Brunei"),
    BOLIVIA("Bolivya", "BO", "516", "Bolivia"),
    BRAZIL("Brezilya", "BR", "508", "Brazil"),
    BAHAMAS("Bahamalar", "BS", "453", "Bahamas"),
    BHUTAN("Butan", "BT", "675", "Bhutan"),
    BOUVET_ISLANDS("Bouvet Adaları", "BV", "892", "Bouvet Islands"),
    BOTSWANA("Botsvana", "BW", "391", "Botswana"),
    BELARUS("Beyaz Rusya", "BY", "073", "Belarus"),
    BELIZE("Belize", "BZ", "421", "Belize"),
    CANADA("Kanada", "CA", "404", "Canada"),
    COCOS_ISLANDS("Cocos Adaları", "CC", "833", "Cocos Islands"),
    ZAIRE("KONGO, DEMOKRATIK HALK CUMHURIYETI", "CD", "322", "ZAIRE(Congo Dem.Rep)"),
    CENTRAL_AFRICAN_REP("Orta Afrika Cumhuriyeti", "CF", "306", "Central African Rep."),
    CONGO("Kongo", "CG", "318", "Congo"),
    SWITZERLAND("İsviçre", "CH", "039", "Switzerland"),
    IVORY_COAST("Fildişi Kıyısı", "CI", "272", "Ivory Coast"),
    COOK_ISLANDS("Cook Adaları", "CK", "837", "Cook Islands"),
    CHILE("Şili", "CL", "512", "Chile"),
    CAMEROON("Kamerun", "CM", "302", "Cameroon"),
    CHINA("Çin", "CN", "720", "China"),
    COLOMBIA("Kolombiya", "CO", "480", "Colombia"),
    COSTA_RICA("Kostarika", "CR", "436", "Costa Rica"),
    TURK_REP_NOR_CYP("Kuzey Kıbrıs Türk Cumhuriyeti", "CT", "601", "Turk Rep.Nor.Cyp."),
    CUBA("Küba", "CU", "448", "Cuba"),
    CAPE_VERDE("Cape Verde", "CV", "247", "Cape Verde"),
    CHRISTMAS_ISLANDS("Christmas Adaları", "CX", "834", "Christmas Islands"),
    SOUTH_CYPRUS("Güney Kıbrıs", "CY", "600", "South Cyprus"),
    CZECH_REPUBLIC("Çek Cumhuriyeti", "CZ", "061", "Czech Republic"),
    GERMANY("Almanya", "DE", "004", "Germany"),
    DJIBOUTI("Cibuti", "DJ", "338", "Djibouti"),
    DENMARK("Danimarka", "DK", "008", "Denmark"),
    DOMINICA("Dominik", "DM", "460", "Dominica"),
    DOMINICIA_REP("Dominik Cumhuriyeti", "DO", "456", "Dominicia Rep."),
    ALGERIA("Cezayir", "DZ", "208", "Algeria"),
    ECUADOR("Ekvator", "EC", "500", "Ecuador"),
    ESTONIA("Estonya", "EE", "053", "Estonia"),
    EGYPT("Mısır", "EG", "220", "Egypt"),
    ERITREA("Eritre", "ER", "336", "Eritrea"),
    SPAIN("İspanya", "ES", "011", "Spain"),
    ETHIOPIA("Etiopya", "ET", "334", "Ethiopia"),
    FINLAND("Finlandiya", "FI", "032", "Finland"),
    FIJI("Fiji", "FJ", "815", "Fiji"),
    FALKLAND_ISLANDS("Falkland Adaları", "FK", "529", "Falkland Islands"),
    MICRONESIA("Mikronezya Federasyonu", "FM", "823", "Micronesia"),
    FAROE_ISLANDS("Faroe Adaları", "FO", "041", "Faroe islands"),
    FRANCE("Fransa", "FR", "001", "France"),
    GABON("Gabon", "GA", "314", "Gabon"),
    UNITED_KINGDOM("İngiltere", "GB", "006", "United Kingdom"),
    GRENADA("Grenada", "GD", "473", "Grenada"),
    GEORGIA("Gürcistan", "GE", "076", "Georgia"),
    GHANA("Gana", "GH", "276", "Ghana"),
    GIBRALTAR("Cebelitarık", "GI", "044", "Gibraltar"),
    GREENLAND("Grönland", "GL", "406", "Greenland"),
    GAMBIA("Gambiya", "GM", "252", "Gambia"),
    GUINEA("Gine", "GN", "260", "Guinea"),
    EQUATORIAL_GUINEA("Ekvator Ginesi", "GQ", "310", "Equatorial Guinea"),
    GREECE("Yunanistan", "GR", "009", "Greece"),
    S_GEOR_AND_SAND("Güney Gürcistan ve Güney Sandviç Adaları", "GS", "893", "S.Geor.And Sand."),
    GUATEMALA("Guatemala", "GT", "416", "Guatemala"),
    GUAM("Guam", "GU", "831", "Guam"),
    GUINEA_BISSAU("Gine Bissau", "GW", "257", "Guinea-Bissau"),
    GUYANA("Guyana", "GY", "488", "Guyana"),
    HONG_KONG("Hong Kong", "HK", "740", "Hong Kong"),
    HEARD_AND_MCDON_IS("Heard ve McDonald Adaları", "HM", "835", "Heard And Mcdon.Is."),
    HONDURAS("Honduras", "HN", "424", "Honduras"),
    CROATIA("Hırvatistan", "HR", "092", "Croatia"),
    HAITI("Haiti", "HT", "452", "Haiti"),
    HUNGARY("Macaristan", "HU", "064", "Hungary"),
    INDONESIA("Endonezya", "ID", "700", "Indonesia"),
    IRELAND("İrlanda", "IE", "007", "Ireland"),
    ISRAEL("İsrail", "IL", "624", "Israel"),
    INDIA("Hindistan", "IN", "664", "India"),
    BRITISH_IND_OCE_TER("İngiliz Hint Okyanus bölgesi", "IO", "357", "British ind.Oce.Ter."),
    IRAQ("Irak", "IQ", "612", "Iraq"),
    IRAN("İran İslam Cumhuriyeti", "IR", "616", "Iran"),
    ICELAND("İzlanda", "IS", "024", "Iceland"),
    ITALY("İtalya", "IT", "005", "Italy"),
    JAMAICA("Jamaika", "JM", "464", "Jamaica"),
    JORDAN("Ürdün", "JO", "628", "Jordan"),
    JAPAN("Japonya", "JP", "732", "Japan"),
    KENYA("Kenya", "KE", "346", "Kenya"),
    KYRGYZSTAN("Kırgızistan Cumhuriyeti", "KG", "083", "Kyrgyzstan"),
    CAMBODIA("Kamboçya", "KH", "696", "Cambodia"),
    KIRIBATI("Kiribati", "KI", "812", "Kiribati"),
    COMOROS("Komorolar", "KM", "375", "Comoros"),
    ST_KITTS_AND_NEVIS("St.Kitts ve Nevis", "KN", "449", "St Kitts And Nevis"),
    NORTH_KOREA("KUZEY KORE (Kore Demorak Halk Cumhuriyeti )", "KP", "724", "North Korea"),
    SOUTH_KOREA("GÜNEY KORE (Kore Cumhuriyeti )", "KR", "728", "South Korea"),
    KUWAIT("Kuveyt", "KW", "636", "Kuwait"),
    CAYMAN_ISLANDS("Cayman Adaları", "KY", "463", "Cayman Islands"),
    KAZAKHSTAN("Kazakistan", "KZ", "079", "Kazakhstan"),
    LAOS("Lao Halk Demokratik Cumhuriyeti", "LA", "684", "Laos"),
    LEBANON("Lübnan", "LB", "604", "Lebanon"),
    ST_LUCIA("St Lucia", "LC", "465", "St Lucia"),
    LIECHTENSTEIN("Liechtenstein", "LI", "037", "Liechtenstein"),
    SRI_LANKA("Sri Lanka", "LK", "669", "Sri Lanka"),
    LIBERIA("Liberya", "LR", "268", "Liberia"),
    LESOTHO("Lesotho", "LS", "395", "Lesotho"),
    LITHUANIA("Litvanya", "LT", "055", "Lithuania"),
    LUXEMBOURG("Lüksemburg", "LU", "018", "Luxembourg"),
    LATVIA("Letonya", "LV", "054", "Latvia"),
    LIBYA("LIBYA ARAB CUMHURIYETI ( Libya)", "LY", "216", "Libya"),
    MOROCCO("Fas", "MA", "204", "Morocco"),
    MOLDOVA("Moldova Cumhuriyeti", "MD", "074", "Moldova"),
    MONTENEGRO("Karadağ", "ME", "094", "Montenegro"),
    MADAGASCAR("Madagaskar", "MG", "370", "Madagascar"),
    MARSHALL_ISLANDS("Marshall Adaları", "MH", "824", "Marshall Islands"),
    MAKEDONIA("MEKODONYA (eski Yugoslavya Cumhuriyeti)", "MK", "096", "Makedonia"),
    MALI("Mali", "ML", "232", "Mali"),
    MYANMAR("Burma", "MM", "676", "Myanmar"),
    MONGOLIA("Moğolistan", "MN", "716", "Mongolia"),
    MACAO("Makao", "MO", "743", "Macao"),
    NORTH_MARIANA_IS("Kuzey Mariana Adaları", "MP", "820", "North Mariana Is."),
    MAURITANIA("Moritanya", "MR", "228", "Mauritania"),
    MONTSERRAT("Montserrat", "MS", "470", "Montserrat"),
    MALTA("Malta", "MT", "046", "Malta"),
    MAURITIUS("Maritus", "MU", "373", "Mauritius"),
    MALDIVES("Maldivler", "MV", "667", "Maldives"),
    MALAWI("Malavi", "MW", "386", "Malawi"),
    MEXICO("Meksika", "MX", "412", "Mexico"),
    MALAYSIA("Malezya", "MY", "701", "Malaysia"),
    MOZAMBIQUE("Mozambik", "MZ", "366", "Mozambique"),
    NAMIBIA("Namibya", "NA", "389", "Namibia"),
    NEW_CALEDONIA("Yeni Kaledonya", "NC", "809", "New Caledonia"),
    NIGER("Nijer", "NE", "240", "Niger"),
    NORFOLK_ISLANDS("Norfolk Adaları", "NF", "836", "Norfolk Islands"),
    NIGERIA("Nijerya", "NG", "288", "Nigeria"),
    NICARAGUA("Nikaragua", "NI", "432", "Nicaragua"),
    NETHERLANDS("Hollanda", "NL", "003", "Netherlands"),
    NORWAY("Norveç", "NO", "028", "Norway"),
    NEPAL("Nepal", "NP", "672", "Nepal"),
    NAURU("Nauru", "NR", "803", "Nauru"),
    NIUE_ISLAND("Niue", "NU", "838", "Niue Island"),
    NEW_ZEALAND("Yeni Zelanda", "NZ", "804", "New Zealand"),
    OMAN("Umman", "OM", "649", "Oman"),
    PANAMA("Panama", "PA", "442", "Panama"),
    PERU("Peru", "PE", "504", "Peru"),
    FRENCH_POLIN("Fransız Polinezyası", "PF", "822", "French Polin."),
    PAPUA_NEW_GUINE("Papua Yeni Gine", "PG", "801", "Papua New Guine"),
    PHILIPPINES("Filipinler", "PH", "708", "Philippines"),
    PAKISTAN("Pakistan", "PK", "662", "Pakistan"),
    POLAND("Polonya", "PL", "060", "Poland"),
    ST_PIERREE("St Pierre and Miquelon", "PM", "408", "St Pierree"),
    PITCAIRN("Pitcairn", "PN", "813", "Pitcairn"),
    PALESTINE("FILISTIN (İşgal edilmiş bölge )", "PS", "625", "Palestine"),
    PORTUGAL("Portekiz", "PT", "010", "Portugal"),
    PALAU("Palau", "PW", "825", "Palau"),
    PARAGUAY("Paraguay", "PY", "520", "Paraguay"),
    QATAR("Katar", "QA", "644", "Qatar"),
    ROMANIA("Romanya", "RO", "066", "Romania"),
    RUSSIA("Rusya Federasyonu", "RU", "075", "Russia"),
    RWANDA("Ruanda", "RW", "324", "Rwanda"),
    SAUDI_ARABIA("Suudi Arabistan", "SA", "632", "Saudi Arabia"),
    SOLOMON_ISL("Solomon Adaları", "SB", "806", "Solomon Isl."),
    SEYCHELLES("Şeyseller", "SC", "355", "Seychelles"),
    SUDAN("Sudan", "SD", "224", "Sudan"),
    SWEDEN("İsveç", "SE", "030", "Sweden"),
    SINGAPORE("Singapur", "SG", "706", "Singapore"),
    ST_HELENA_AND_DEP("Saint Helena", "SH", "329", "St Helena And Dep."),
    SLOVENIA("Slovenya", "SI", "091", "Slovenia"),
    SLOVAKIA("Slovakya", "SK", "063", "Slovakia"),
    SIERRA_LEONE("Sierra Leone", "SL", "264", "Sierra Leone"),
    SAN_MARINO("San Marino", "SM", "047", "San Marino"),
    SENEGAL("Senegal", "SN", "248", "Senegal"),
    SOMALIA("Somali", "SO", "342", "Somalia"),
    SURINAM("Surinam", "SR", "492", "Surinam"),
    SAO_TOME_AND_PRIN("Sao Tome ve Prinsip", "ST", "311", "Sao Tome And Prin."),
    EL_SALVADOR("El Salvador", "SV", "428", "El Salvador"),
    SYRIA("SURIYE (Suriye Arab Cumhuriyeti)", "SY", "608", "Syria"),
    SWAZILAND("Svaziland", "SZ", "393", "Swaziland"),
    TURKS_AND_CA_ISL("Türk ve Caicos Adları", "TC", "454", "Turks And Ca.isl"),
    CHAD("Çad", "TD", "244", "Chad"),
    FRENCH_SOUTH_TE("Fransa Güney Bölgsei", "TF", "894", "French South.Te."),
    TOGO("Togo", "TG", "280", "Togo"),
    THAILAND("Tayland", "TH", "680", "Thailand"),
    TAJIKISTAN("Tacikistan", "TJ", "082", "Tajikistan"),
    TOKELAU_ISLANDS("Tokelau", "TK", "839", "Tokelau Islands"),
    EAST_TIMOR("Timor", "TL", "626", "East Timor"),
    TURKMENISTAN("Türkmenistan", "TM", "080", "Turkmenistan"),
    TUNISIA("Tunus", "TN", "212", "Tunisia"),
    TONGA("Tonga", "TO", "817", "Tonga"),
    TURKEY("Türkiye", "TR", "052", "Turkey"),
    TRINIDAD_AND_TOBAGO("Trinidad ve Tobago", "TT", "472", "Trinidad And Tobago"),
    TUVALU("Tuvalu", "TV", "807", "Tuvalu"),
    TAIWAN("Tayvan", "TW", "736", "Taiwan"),
    TANZANIA("Tanzania Birleşik Cumhuriyeti", "TZ", "352", "Tanzania"),
    UKRAINE("Ukrayna", "UA", "072", "Ukraine"),
    UGANDA("Uganda", "UG", "350", "Uganda"),
    USA_MINOR_OUTLYIN("Amerika Birleşik Devletleri Küçük Out Adları", "UM", "832", "USA Minor Outlyin"),
    USA("Amerika Birleşik Devletleri", "US", "400", "USA"),
    URUGUAY("Uruguay", "UY", "524", "Uruguay"),
    UZBEKISTAN("Özbekistan", "UZ", "081", "Uzbekistan"),
    VATICAN_CITY_ST("Vatikan", "VA", "045", "Vatican City St"),
    ST_VINCENT("St Vincent and the Grenadines", "VC", "467", "St Vincent"),
    VENEZUELA("Venezuella", "VE", "484", "Venezuela"),
    BRITISH_VIRGIN_ISL("İngiliz Virjin Adları", "VG", "468", "British Virgin Isl."),
    USA_VIRGIN_ISL("Virjin Adları Amerika Birleşik Devletleri", "VI", "457", "USA Virgin Isl."),
    VIETNAM("Vietnam", "VN", "690", "Vietnam"),
    VANUATU("Vanuatu", "VU", "816", "Vanuatu"),
    VALLIS_AND_FORTUNA("Wallis ve Futuna", "WF", "811", "Vallis And Fortuna"),
    SAMOA("Samoa", "WS", "819", "Samoa"),
    CEUTA("Ceuta", "XC", "021", "Ceuta"),
    KOSOVO("Kosova", "XK", "094", "Kosovo"),
    MELILLA("Mellila", "XL", "023", "Melilla"),
    SERBIA_("Sirbistan", "XS", "098", "Serbia "),
    YEMEN("Yemen", "YE", "653", "Yemen"),
    MAYOTTE("Mayotte", "YT", "377", "Mayotte"),
    SOUTH_AFRICA("Güney Afrika", "ZA", "388", "South Africa"),
    ZAMBIA("Zambia", "ZM", "378", "Zambia"),
    ZIMBABWE("Zimbabve", "ZW", "382", "Zimbabwe");

    private final String label;
    private final String harfKodu;
    private final String kodu;
    private final String englishName;

    private Ulke(String label, String harfKodu, String kodu, String englishName) {
        this.label = label;
        this.harfKodu = harfKodu;
        this.kodu = kodu;
        this.englishName = englishName;
    }

    @Override
    public String getLabel() {
        return label;
    }
}
