package belge;

import tr.com.innova.sample.common.utils.Displayable;

/**
 * Created by herdemir on 10.06.2015.
 */
public enum BelgeTipi implements Displayable {
    ARA_KARAR("Ara Karar"),
    BELGE("Belge"),
    BILIRKISI_RAPORU("Bilirkişi Raporu"),
    BORCLU_MEKTUBU("Borçlu Mektubu"),
    CEVABA_CEVAP_DILEKCESI("Cevaba Cevap Dilekçesi"),
    CEVAP_DILEKCESI("Cevap Dilekçesi"),
    DANISTAY_KARARI("Danıştay Kararı"),
    DAVA_DILEKCESI("Dava Dilekçesi"),
    DEKONT("Dekont"),
    DELIL_LISTESI("Delil Listesi"),
    DERKENAR("Derkenar"),
    DILEKCE("Dilekçe"),
    DIGER("Diğer"),
    DURUSMA_TUTANAGI("Duruşma Tutanağı"),
    E_MAIL("E-Mail"),
    EMSAL_YARGITAY_KARARI("Emsal Yargıtay Kararı"),
    FATURA("Fatura"),
    FORM("Form"),
    GEREKCELI_KARAR("Gerekçeli Karar"),
    GIDER_PUSULASI("Gider Pusulası"),
    GONDERILEN_EVRAK("Gönderilen Evrak"),
    GORUSME_KAYITLARI("Görüşme Kayıtları"),
    GORUSME_TUTANAGI("Görüşme Tutanağı"),
    GUNLUK_MUSTERI_LISTESI("Günlük Müşteri Listesi"),
    GUVENLIK_GUCU_TALEBI("Güvenlik Gücü Talebi"),
    GUVENLIK_SERTIFIKASI("Güvenlik Sertifikası"),
    HARC_MAKBUZU("Harç Makbuzu"),
    HASAR_KESIF_TUTANAGI("Hasar Keşif Tutanağı"),
    HASAR_TESPIT_TUTANAGI("Hasar Tespit Tutanağı"),
    HUKUKI_MUTALAA("Hukuki Mütalaa"),
    KAMPANYA_TAAHHUTNAMESI("Kampanya Taahhütnamesi"),
    KAPAK_HESABI("Kapak Hesabı"),
    KARAR("Karar"),
    KARAR_ORNEKLERI("Karar Örnekleri"),
    KEFALETNAME("Kefaletname"),
    KESIF_TUTANAGI("Keşif Tutanağı"),
    KIRA_SOZLESMESI("Kira Sözleşmesi"),
    KOMISYON_KARARI("Komisyon Kararı"),
    MAHKEME_ILAMLARI("Mahkeme İlamları"),
    MAKAM_ONAYI("Makam Onayı"),
    MEHIL_VESIKASI("Mehil Vesikası"),
    MUHTIRA("Muhtıra"),
    MURAFAA("Mürafaa"),
    MUSTAHSIL_MAKBUZU("Müstahsil Makbuzu"),
    MUZEKKERE("Müzekkere"),
    OLAY_YERI_TESPIT_TUTANAGI("Olay Yeri Tespit Tutanağı"),
    PERAKENDE_SATIS_VESIKASI("Perakende Satış Vesikası"),
    REDDIYAT("Reddiyat"),
    SAVCILIK_SIKAYET_DILEKCESI("Savcılık Şikayet Dilekçesi"),
    SERBEST_MESLEK_MAKBUZU("Serbest Meslek Makbuzu"),
    SEVK_IRSALIYESI("Sevk İrsaliyesi"),
    SIGORTA_POLICESI("Sigorta Poliçesi"),
    SOZLESME("Sözleşme"),
    TAAHUTNAME("Taahütname"),
    TASIMA_IRSALIYESI("Taşıma İrsaliyesi"),
    TEBLIGAT("Tebligat"),
    TEMINAT_MEKTUBU("Teminat Mektubu"),
    TEMYIZ_DILEKCESI("Temyiz Dilekçesi"),
    TENSIP_TUTANAGI("Tensip Tutanağı"),
    TEVZI_FORMU("Tevzi Formu"),
    TRAFIK_KAZASI_TESPIT_TUTANAGI("Trafik Kazası Tespit Tutanağı"),
    TUTANAK("Tutanak"),
    TUKETICI_HAKEM_HEYETI_KARARI("Tüketici Hakem Heyeti Kararı"),
    VEKIL_AVUKATLIK_SOZLESMESI("Vekil Avukatlık Sözleşmesi"),
    VEKIL_KULLANICI_BILGI_FORMU("Vekil Kullanıcı Bilgi Formu"),
    VEKIL_VEKALETNAME_ORNEGI("Vekil Vekaletname Örneği"),
    VEKIL_ISTIFA_IBRANAME("Vekil İstifa İbraname"),
    VERGI_MAKBUZLARI("Vergi Makbuzları"),
    YARGITAY_ILAMI("Yargıtay İlamı"),
    YOLCU_LISTESI("Yolcu Listesi"),
    CAGRI_KAGIDI("Çağrı Kağıdı"),
    ODEME_EMRI("Ödeme Emri"),
    UCRET_BORDROSU("Ücret Bordrosu"),
    ICRA_DOSYASI_KAPAK_HESABI("İcra Dosyası Kapak Hesabı"),
    ICRA_EMRI("İcra Emri"),
    IDDIANAME("İddianame"),
    IHBARNAME("İhbarname"),
    IHTARNAME("İhtarname"),
    INCELEME_RAPORU("İnceleme Raporu"),
    INCELEME_TUTANAGI("İnceleme Tutanağı"),
    IRSALIYELI_FATURA("İrsaliyeli Fatura"),
    TEBLIG_ZARFI("Tebliğ Zarfı"),
    _89_1_2_3_HACIZ_IHBARNAMESI("89/1-2-3 Haciz İhbarnamesi"),
    HACIZ_FEKKI("Haciz Fekki"),
    MAAS_HACZI_TEKID("Maaş Haczi-Tekid"),
    YEDIEMIN_MENKUL_MAL_TESLIMI("Yediemin Menkul Mal Teslimi"),
    YEDIEMIN_MUHTIRA("Yediemin Muhtıra"),
    YEDIEMIN_DEGISTIRME_ZAPTI("Yediemin Değiştirme Zaptı"),
    IPOTEGIN_KALDIRILMASI_ILE_ILGILI_BELGE("İpoteğin Kaldırılması ile İlgili Belge"),
    _100_MADDE_ILE_ILGILI_BELGE("100 Madde ile İlgili Belge"),
    ISTIHKAK_IDDIASININ_BILDIRILMESINE_ILISKIN_BELGE("İstihkak İddiasının Bildirilmesine İlişkin Belge"),
    ODEME_ICRA_TAHLIYE_EMRI("Ödeme/İcra/Tahliye Emri"),
    DAVET_KAGIDI("Davet Kağıdı"),
    ALINDI_MAKBUZU("Alındı Makbuzu"),
    ITIRAZ_BELGESI("İtiraz Belgesi"),
    HACIZ_TUTANAGI("Haciz Tutanağı"),
    ACIK_ARTIRMA_SARTNAMESI_VE_TUTANAGI("Açık Artırma Şartnamesi ve Tutanağı"),
    ACIZ_VESIKASI("Aciz Vesikası"),
    ILAMIN_ICRASI("İlamın İcrası"),
    REHIN_ACIGI_BELGESI("Rehin Açığı Belgesi"),
    ILAN("İlan"),
    SIRA_CETVELI("Sıra Cetveli"),
    TAHSILAT_MAKBUZU("Tahsilat Makbuzu"),
    REDDIYAT_MAKBUZU("Reddiyat Makbuzu"),
    TEVDI_LISTESI("Tevdi Listesi"),
    TAKIP_TALEBI("Takip Talebi"),
    TEBLIG_TALEBI("Tebliğ Talebi"),
    ADRES_ARASTIRMA_TALEBI("Adres Araştırma Talebi"),
    MVA_VE_HACIZ_TALEBI("MVA ve Haciz Talebi"),
    HACIZ_TALEBI("Haciz Talebi"),
    ARAC_MUHAFAZASI_TALEBI("Araç Muhafazası Talebi"),
    KIYMET_TAKDIRI_TALEBI("Kıymet Takdiri Talebi"),
    SATIS_TALEBI("Satış Talebi"),
    HACIZ_FEKKI_TALEBI("Haciz Fekki Talebi"),
    ADRES_ARASTIRMA_MUZEKKERESI("Adres Araştırma Müzekkeresi"),
    MVA_VE_HACIZ_MUZEKKERESI("MVA ve Haciz Müzekkeresi"),
    ARAC_MUHAFAZASI_MUZEKKERESI("Araç Muhafazası Müzekkeresi"),
    SATIS_MUZEKKERESI("Satış Müzekkeresi"),
    HACZIN_FEKKI_MUZEKKERESI("Haczin Fekki Müzekkeresi"),
    HARC_TAHSIL_MUZEKKERESI("Harç Tahsil Müzekkeresi"),
    IHZAR_MUZEKKERESI("İhzar Müzekkeresi"),
    TEMINATIN_IADESI_MUZEKKERESI("Teminatın İadesi Müzekkeresi"),
    TALIMAT_DOKUM("Talimat Döküm"),
    TEHIR_I_ICRA_DOKUM("Tehir-i İcra Döküm"),
    MEKTUPLAR("Mektuplar"),
    _100_MADDE_ILGILI_BELGE("100 Madde İlgili Belge"),
    IPOTEK_ISLEMLERI_BELGESI("İpotek İşlemleri Belgesi");

    private final String label;

    BelgeTipi(String label) {
        this.label = label;
    }

    @Override
    public String getLabel() {
        return label;
    }
}
